# Generated by Django 2.0.2 on 2018-02-21 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
                ('handle', models.CharField(max_length=280)),
                ('tweet_id', models.IntegerField()),
                ('body', models.CharField(max_length=400)),
                ('link', models.CharField(max_length=400)),
                ('datetime', models.DateTimeField()),
                ('replies', models.IntegerField()),
                ('rts', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=280)),
                ('handle', models.CharField(max_length=280)),
                ('profile_link', models.CharField(max_length=300)),
                ('pic_ref', models.CharField(max_length=300)),
                ('tweets', models.IntegerField()),
                ('followers', models.IntegerField()),
                ('following', models.IntegerField()),
            ],
        ),
    ]
