# Generated by Django 2.0.2 on 2018-02-20 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('handle', models.CharField(max_length=200)),
                ('tweet_id', models.IntegerField()),
                ('body', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=200)),
                ('datetime', models.DateTimeField()),
                ('replies', models.IntegerField()),
                ('rts', models.IntegerField()),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
